name: Syntax Checking and Linting
on:
  [pull_request]
    
jobs:
  build:
    name: Linting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # YAML Linter
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v0.0.1
        with:
          file_or_dir: .

      # PHP Check linter
      - name: PHP Syntax Checker (Lint) PHP 8.1
        uses: StephaneBour/actions-php-lint@8.1
        with:
          dir: '.'
